### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [CreativeMD/AmbientSounds#13] opened 2017-07-20 15:20 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  LoadingPlugin (Quark-r1.2-101.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.2.0.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/20/17 4:18 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at paulscode.sound.SoundSystem.stop(SoundSystem.java:1188)
	at com.creativemd.ambientsounds.AmbientSoundEngine.stop(AmbientSoundEngine.java:241)
	at com.creativemd.ambientsounds.AmbientSound.stopSound(AmbientSound.java:220)
	at com.creativemd.ambientsounds.AmbientSound.tick(AmbientSound.java:238)
	at com.creativemd.ambientsounds.TickHandler.onTick(TickHandler.java:241)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_239_TickHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at paulscode.sound.SoundSystem.stop(SoundSystem.java:1188)
	at com.creativemd.ambientsounds.AmbientSoundEngine.stop(AmbientSoundEngine.java:241)
	at com.creativemd.ambientsounds.AmbientSound.stopSound(AmbientSound.java:220)
	at com.creativemd.ambientsounds.AmbientSound.tick(AmbientSound.java:238)
	at com.creativemd.ambientsounds.TickHandler.onTick(TickHandler.java:241)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_239_TickHandler_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['nexusdog'/170, l='MpServer', x=235.21, y=69.00, z=-142.13]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,-140), Chunk: (at 0,4,4 in 12,-9; contains blocks 192,0,-144 to 207,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 151488 game time, 1715807 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 68 total; [EntityItem['item.item.egg'/3843, l='MpServer', x=264.26, y=68.00, z=-180.13], EntitySkeleton['Skeleton'/5381, l='MpServer', x=177.50, y=16.00, z=-112.50], EntityBat['Bat'/5126, l='MpServer', x=208.48, y=14.10, z=-70.25], EntityZombie['Zombie'/5386, l='MpServer', x=235.50, y=28.00, z=-96.50], EntityZombie['Zombie'/5387, l='MpServer', x=231.50, y=28.00, z=-99.19], EntityZombie['Zombie'/4108, l='MpServer', x=241.55, y=21.00, z=-71.09], EntityZombie['Zombie'/5388, l='MpServer', x=231.50, y=28.00, z=-96.30], EntityCreeper['Creeper'/4885, l='MpServer', x=309.50, y=22.00, z=-129.50], EntityCreeper['Creeper'/5658, l='MpServer', x=259.50, y=40.00, z=-114.50], EntityCreeper['Creeper'/4641, l='MpServer', x=213.69, y=48.00, z=-84.49], EntityZombie['Zombie'/5666, l='MpServer', x=283.50, y=33.00, z=-83.50], EntityItem['item.tile.vine'/5159, l='MpServer', x=238.08, y=71.00, z=-147.65], EntityZombie['Zombie'/5420, l='MpServer', x=280.19, y=15.00, z=-116.50], EntityZombie['Zombie'/5421, l='MpServer', x=278.50, y=14.00, z=-116.50], EntityBat['Bat'/5686, l='MpServer', x=263.31, y=21.07, z=-94.46], EntitySheep['Sheep'/68, l='MpServer', x=200.29, y=89.00, z=-132.49], EntitySheep['Sheep'/69, l='MpServer', x=200.26, y=89.00, z=-120.52], EntityBat['Bat'/4677, l='MpServer', x=280.55, y=15.52, z=-113.86], EntitySheep['Sheep'/70, l='MpServer', x=199.27, y=89.00, z=-126.49], EntityZombie['Zombie'/4937, l='MpServer', x=213.50, y=33.00, z=-183.50], EntitySheep['Sheep'/82, l='MpServer', x=209.00, y=89.00, z=-115.48], EntityCreeper['Creeper'/5459, l='MpServer', x=298.50, y=20.00, z=-132.50], EntityZombie['Zombie'/5211, l='MpServer', x=297.50, y=47.00, z=-126.50], EntityPig['Pig'/97, l='MpServer', x=235.70, y=73.00, z=-209.51], EntityChicken['Chicken'/98, l='MpServer', x=230.79, y=77.00, z=-216.51], EntityBat['Bat'/5218, l='MpServer', x=264.58, y=13.23, z=-103.30], EntityChicken['Chicken'/99, l='MpServer', x=238.15, y=74.00, z=-211.43], EntityWorm['Worm'/103, l='MpServer', x=228.50, y=62.50, z=-135.50], EntityWorm['Worm'/104, l='MpServer', x=228.50, y=62.50, z=-132.50], EntityWorm['Worm'/105, l='MpServer', x=226.50, y=62.50, z=-131.50], EntityWorm['Worm'/106, l='MpServer', x=226.50, y=62.50, z=-136.50], EntityWorm['Worm'/107, l='MpServer', x=234.50, y=62.50, z=-134.50], EntityWorm['Worm'/108, l='MpServer', x=234.50, y=62.50, z=-131.50], EntityWorm['Worm'/109, l='MpServer', x=237.50, y=62.50, z=-131.50], EntityWorm['Worm'/110, l='MpServer', x=237.50, y=62.50, z=-134.50], EntityZombie['Zombie'/5486, l='MpServer', x=173.75, y=20.00, z=-125.54], EntityWorm['Worm'/111, l='MpServer', x=231.50, y=62.50, z=-131.50], EntityChicken['Chicken'/117, l='MpServer', x=262.19, y=69.00, z=-193.49], EntitySpider['Spider'/5238, l='MpServer', x=260.50, y=19.00, z=-93.50], EntitySkeleton['Skeleton'/5495, l='MpServer', x=282.50, y=32.00, z=-88.50], EntitySkeleton['Skeleton'/120, l='MpServer', x=244.51, y=46.00, z=-141.32], EntityCreeper['Creeper'/4986, l='MpServer', x=210.50, y=20.00, z=-95.50], EntityCreeper['Creeper'/5242, l='MpServer', x=157.50, y=17.00, z=-89.50], EntityChicken['Chicken'/126, l='MpServer', x=272.42, y=70.00, z=-219.49], EntityZombie['Zombie'/5246, l='MpServer', x=212.50, y=19.00, z=-94.50], EntityChicken['Chicken'/128, l='MpServer', x=264.57, y=68.00, z=-180.82], EntityZombie['Zombie'/5248, l='MpServer', x=212.50, y=19.00, z=-94.50], EntitySquid['Squid'/5506, l='MpServer', x=281.78, y=58.15, z=-104.09], EntitySquid['Squid'/5507, l='MpServer', x=272.79, y=59.79, z=-101.29], EntitySquid['Squid'/5508, l='MpServer', x=290.49, y=55.77, z=-100.50], EntitySquid['Squid'/5509, l='MpServer', x=279.22, y=58.76, z=-108.97], EntityChicken['Chicken'/134, l='MpServer', x=283.92, y=68.00, z=-216.50], EntityChicken['Chicken'/135, l='MpServer', x=283.51, y=68.00, z=-215.52], EntityBat['Bat'/4512, l='MpServer', x=231.75, y=29.10, z=-101.25], EntityBat['Bat'/5024, l='MpServer', x=219.01, y=26.64, z=-178.73], EntitySquid['Squid'/5544, l='MpServer', x=298.33, y=59.24, z=-175.32], EntityBat['Bat'/3754, l='MpServer', x=245.25, y=48.10, z=-164.75], EntityWitch['Witch'/4783, l='MpServer', x=263.50, y=19.00, z=-93.50], EntityCreeper['Creeper'/5046, l='MpServer', x=181.50, y=26.00, z=-110.50], EntityCreeper['Creeper'/4535, l='MpServer', x=205.50, y=20.00, z=-136.50], EntitySkeleton['Skeleton'/5304, l='MpServer', x=233.50, y=30.00, z=-99.50], EntityPlayerSP['nexusdog'/170, l='MpServer', x=235.21, y=69.00, z=-142.13], EntityZombie['Zombie'/5331, l='MpServer', x=198.50, y=61.00, z=-204.50], EntityItem['item.item.slimeball'/4060, l='MpServer', x=293.16, y=18.00, z=-107.49], EntityCreeper['Creeper'/4322, l='MpServer', x=303.50, y=20.00, z=-134.50], EntityBat['Bat'/5615, l='MpServer', x=300.75, y=14.37, z=-106.25], EntityBat['Bat'/5368, l='MpServer', x=201.50, y=33.70, z=-71.60], EntityBat['Bat'/5373, l='MpServer', x=178.17, y=32.02, z=-65.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1410210872 bytes (1344 MB) / 3497889792 bytes (3335 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.40 Powered by Forge 14.21.1.2415 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAA	forge{14.21.1.2415} [Minecraft Forge] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.2.0} [Backpacks!] (zz-backpacks 1.12 - 3.2.0.jar) 
	UCHIJAAAA	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCHIJAAAA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.6 mc1.12.jar) 
	UCHIJAAAA	quark{r1.2-101} [Quark] (Quark-r1.2-101.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHIJAAAA	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCHIJAAAA	crafttweaker{4.0.1} [CraftTweaker2] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	caravans{{version}} [Caravans] (Caravans-0.1.2-1.12.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.3 mc1.12.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UCHIJAAAA	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCHIJAAAA	cyclicmagic{1.6.1} [Cyclic] (Cyclic-1.12-1.6.1.jar) 
	UCHIJAAAA	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCHIJAAAA	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCHIJAAAA	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCHIJAAAA	movingworld{1.12-4.340} [Moving World] (movingworld-1.12-4.340-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-4.334-full.jar) 
	UCHIJAAAA	dsurround{3.4.6.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHIJAAAA	presets{3.4.6.0} [§3Presets!] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHIJAAAA	eim{1.0} [eim] (EIM-1.0.0.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	csb_ench_table{1.1.2-beta2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2-beta2.jar) 
	UCHIJAAAA	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCHIJAAAA	everlastingabilities{1.3.1} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.1.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UCHIJAAAA	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCHIJAAAA	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCHIJAAAA	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCHIJAAAA	funores{1.5.5} [Fun Ores] (FunOres-1.12-1.5.5-113.jar) 
	UCHIJAAAA	gamestages{1.0.12} [Game Stages] (GameStages-1.12-1.0.12.jar) 
	UCHIJAAAA	goodluckskeleton{1.0} [Good Luck Skeleton] (goodluckskeleton-1.1-MC1.12.jar) 
	UCHIJAAAA	gravestone{1.0.11} [Gravestone] (GraveStone-1.12-Graves-1.0.11.jar) 
	UCHIJAAAA	igcm{1.0.0} [InGameConfigManager] (IGCM v1.2.0 pre-1 mc1.12.jar) 
	UCHIJAAAA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.3-1.12.jar) 
	UCHIJAAAA	limelib{1.7.4} [LimeLib] (limelib-1.12-1.7.4.jar) 
	UCHIJAAAA	malisiscore{1.12-6.0.1} [MalisisCore] (malisiscore-1.12-6.0.1.jar) 
	UCHIJAAAA	malisisblocks{1.12-6.0.0} [Malisis Blocks] (malisisblocks-1.12-6.0.0.jar) 
	UCHIJAAAA	malisisdoors{1.12-7.0.2} [MalisisDoors] (malisisdoors-1.12-7.0.2.jar) 
	UCHIJAAAA	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	mendingfix{1.0.1} [Mending Fix] (mendingfix-1.0.1.jar) 
	UCHIJAAAA	minecolonies{1.12-0.8.3167} [MineColonies] (minecolonies-universal-1.12-0.8.3167.jar) 
	UCHIJAAAA	minemenu{1.6.1} [MineMenu] (MineMenu-1.12-1.6.1-universal.jar) 
	UCHIJAAAA	minions{2.0.2} [Minions] (Minions-1.12.jar) 
	UCHIJAAAA	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCHIJAAAA	mobends{0.23.4} [Mo' Bends] (mobends-0.23.4_for_MC-1.12.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCHIJAAAA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJAAAA	ob_stuff{1.1} [MSU: OpenBlocks Stuff] (MSU-OpenBlocks Stuff-1.1.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	packingtape{0.7.4} [Packing Tape] (PackingTape-1.12.0-0.7.4.jar) 
	UCHIJAAAA	harvestcraft{1.11.2i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCHIJAAAA	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
	UCHIJAAAA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJAAAA	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCHIJAAAA	icc{0.2.1} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.1.jar) 
	UCHIJAAAA	simplebedding{1.1.0} [Simple Bedding] (simplebedding-1.1.0.jar) 
	UCHIJAAAA	simplemagnet{1.12.0-1.2.6} [Simple Magnet] (simplemagnet-1.12.0-1.2.6.jar) 
	UCHIJAAAA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCHIJAAAA	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHIJAAAA	sounds_extended{1.8.2-1.12} [Sounds Extended] (sounds extended-1.8.2-1.12.jar) 
	UCHIJAAAA	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCHIJAAAA	thut_wearables{3.0.4} [Thut's Wearables] (thut_wearables-3.0.4.jar) 
	UCHIJAAAA	thutcore{5.5.0} [Thut Core] (thutcore-5.5.0.jar) 
	UCHIJAAAA	thut_bling{2.0.0} [Thut's Bling] (thut_bling-2.0.0.d.jar) 
	UCHIJAAAA	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCHIJAAAA	tombstone{1.2.8} [Corail Tombstone] (tombstone-1.2.8-1.12.0.jar) 
	UCHIJAAAA	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCHIJAAAA	bspkrscore{at_0.9} [bspkrsCore] (Treecapitator-1.12-at_0.9a.jar) 
	UCHIJAAAA	treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.12-at_0.9a.jar) 
	UCHIJAAAA	uncrafted{3.0.0pre2} [Uncrafted Mod] (Uncrafted 1.12 (v.3.0.0pre2).jar) 
	UCHIJAAAA	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCHIJAAAA	vctweaker{@MOD_VERSION@} [ViesCraft Tweaker] (ViesCraftTweaker-1.12-2.0.6.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
LoadingPlugin (Quark-r1.2-101.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
BCModPlugin (zz-backpacks 1.12 - 3.2.0.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Launched Version: 1.12-forge1.12-14.21.1.2415
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TEAVSRP2.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by CreativeMD** [comment] 2017-07-21 13:31
This a duplicate of this issue: https://github.com/CreativeMD/AmbientSounds/issues/7
i can't fix it, we have to wait for the author of the paulscode engine to take care of it.

**Closed as completed by CreativeMD** 2017-07-21 13:31 UTC
