### ISSUE TITLE
My ambient sound is not working at all.

### ISSUE THREAD

**Issue by ngrove21** [CreativeMD/AmbientSounds#139] opened 2022-07-03 15:55 UTC
I just got forge yesterday and I also got optifine to run with a shader I was using. The mod loaded just fine into the system but there is no sound. Any thoughts?

**Comment by ngrove21** [comment] 2022-07-03 15:56
> I just got forge yesterday and I also got optifine to run with a shader I was using. The mod loaded just fine into the system but there is no sound. Any thoughts?

Yes I have my sound on.

**Comment by CreativeMD** [comment] 2022-07-04 16:21
I'm not entirely sure what is causing the issue, but apparently there are some issues with custom sound settings. If the default playback device differs from the system default it might not work.

**Comment by Robiken** [comment] 2022-07-08 11:10
So I've got the same thing. I tried Switching the sound output device both in windows and in-game but no configuration seemed to be working. This is especially concerning if we include the fact that it worked normally just a few hours earlier. I spent some time flying in spectator around the world testing how the mod works in different environments. I lowered the volume of cave sounds and sent a question about them on discord. When I came back after some time the problem first appeared. Tried reloading the game, setting settings to default, and reinstalling both the mod and Creative Core (I'm using fabric). Nothing worked so far :/
Edit: Also I'm using the newest 1.19 version. And the sound works but ONLY in water.

**Comment by Robiken** [comment] 2022-07-09 16:26
If you'll need some more data about my game for some testing or smth let me know

**Comment by Robiken** [comment] 2022-07-09 16:41
![2022-07-09_18 37 17](https://user-images.githubusercontent.com/99271043/178114889-54b6b1d7-56b9-4418-b818-3de540af5ef5.png)

![2022-07-09_18 39 23](https://user-images.githubusercontent.com/99271043/178114931-191ccc63-a0f7-467e-bfa6-239f47ad766b.png)


So I checked on debug mode and it seems like the sounds are playing, I just can't hear them for some reason. As if everything was muted. I checked in the options and everything is set on 1, yet the game plays at volume 0. The only thing That's on 1 is water. Reloading the mod doesn't seem to work.

**Comment by Robiken** [comment] 2022-07-09 16:43
Yes, I'm using Simple voice chat at the screens but it acted exactly the same without any other mods installed. Is there a way to reset settings via a command? ALSO when I play the sound using /playsound everything works just fine so I doubt that this is due to the wrong audio output. I checked that multiple times...

**Comment by Nixoup** [comment] 2022-07-09 18:06
I have the same problem as you, with this versions of Forge, Optifine and the 2 mods :(
![Sans titre 1](https://user-images.githubusercontent.com/78208484/178117782-1964dfd0-6d70-45c3-99bb-8276f45fb590.png)

**Comment by Herobrine7707** [comment] 2022-07-10 06:22
the problem of the mod is also caused by fabric

**Comment by CreativeMD** [comment] 2022-07-11 16:49
@Robiken does it happen if only CreativeCore and AmbientSounds is installed? Did the version for 1.18 work fine? Does ingame music work fine?

@Nixoup that's not how you install forge and optifine (the jar file needs to be in the mods folder). But thanks, because makes sure it's not a fabric specific issue.

**Comment by Nixoup** [comment] 2022-07-11 18:29
@CreativeMD And yet, before 1.19, everything worked like that, I don't understand? :o

So I followed your instructions but it still doesn't work, did I miss something?

**Comment by CreativeMD** [comment] 2022-07-12 18:36
@Nixoup my hint had nothing to do with the issue itself. Just wanted to say if you want to use Optifine and Forge together you need to put Optifine in the mods folder.

**Comment by DewsJaz** [comment] 2022-07-16 17:03
I am on 1.18.2 and this stopped working when I switched to the Optifine Compatible version of Forge (40.0.24) and loaded BSL Shaders.

**Comment by ghost** [comment] 2022-07-24 18:28
Hello, I’m on 1.19 and forge 41.0.63 if i remember it correctly. I’ve the same problem.

I’m also using “Sound physics remastered” and I had no problems at all. I switched to fabric for a short time trying out other mods but later switched again to forge and just copied my forge mod folder I saved before back in.

Now I also can’t hear the sound, only underwater. They are in fact playing in the debug menu but I just can’t hear them.

l’ll do a fresh install of minecraft and everything and see if that works.
My girlfriend got the same mods (we play lan) and she has no problems at all.

If you require any sorts of testing, just tell me. It’s really a weird bug cause I diden’t change anything. I hope we find a solution here :)

**Comment by CreativeMD** [comment] 2022-07-25 09:18
@Hurainzone500  yeah that is weird. Would be good to know if a fresh install does actually fix.

**Comment by ghost** [comment] 2022-07-25 10:25
@CreativeMD Yes it did. I did a fresh install (took a while thanks to mc launchers bugs aswell :D) and downloaded forge 41.0.105 I think (the one which is compatible with the latest optifine preview).

Later inserted my shader, complimentary shaders and only the CC and AS mods, latest versions.

Works as intended :)

But let’s wait until I install sound physics remastered again or boot up my old world cause I created a new one after the fresh install.

EDIT: Everything is still fine after installing the mod and playing my old world. Enjoying the ambience now :)
If I make any changes i‘ll keep an ear on it if it breaks, maybe we know what’s causing the bug then ?!

**Comment by CreativeMD** [comment] 2022-07-26 08:13
@Hurainzone500 thanks for all the information!

I guess a clean install seems to be the solution for now. I guess it is some sort of the issue with Minecrafts audio engine. Minecraft does not stream and loop audio files like AmbientSounds does. It has been an issue before but got fixed. Maybe a clean install removes some old outdated libraries.

**Comment by ghost** [comment] 2022-07-27 17:00
@CreativeMD Your welcome !
If your interested and you still developing the mod further, I have some suggestions for it.
I don’t want to open another topic.

Sometimes in certain Biomes it get‘s a little bit annoying if you here the same bird / crow all the time. I’m not into coding (right now ^^) but maybe it’s possible to add a time variable which determines how often the same sound is played or between the loop.
And the player could adjust it, like a minimum and a maximum time between the sound loops.

Or simply adding more bird /crow or whatever sounds in certain biomes.

I could be more specific but I don’t know exactly how it works, it’s detecting game time, dimension and biomes (mixes biome sounds depending on how close you are to them) ? It’s just what I’ve read from the debug menu ^^
But yeah :D

EDIT: Well, just found the how to create your own engine in the code and there is a “pause”. Have to check the ingame options again... ;)

**Comment by CreativeMD** [comment] 2022-07-29 07:19
@Hurainzone500 yeah take a look at the assets/ambientsounds/basic/ folder in there you can find all the data for the engine. The tutorial is out of date. Sounds for birds are picked randomly, but maybe some biomes do not have enough sounds to choose from. I would need more information of what biome it is to pinpoint the issue.

**Comment by CreativeMD** [comment] 2022-08-20 10:43
Does anyone still have this issue?

**Comment by ghost** [comment] 2022-08-20 11:11
I don´t, the fresh install of mc got rid of it. Never had it again.

**Comment by CreativeMD** [comment] 2022-09-06 14:01
Just out of curiosity. @Hurainzone500 have you ever changed the minecraft volume setting of `Ambient/ Environment`?

**Comment by ghost** [comment] 2022-09-06 14:56
@CreativeMD Yes, i think i did when i first got the mod. I did not knew i could turn down the volume of individiual souds in the mod menu, that´s why i turned down the whole ambient/environment sounds when i was underground.

Since the fresh install, i never touched it since i knew i can change the specific sound in the mod menu.

That might be the cause of the issues at the beginning.
Still using the mod and having no problems :)

**Comment by CreativeMD** [comment] 2022-09-07 11:29
Ok, I will close this issue. If anyone has this issue ever again. Check what happens if you set `useSoundMasterSource` to true in the config and see if it fixes it. If not report it here again.

**Closed as completed by CreativeMD** 2022-09-07 11:29 UTC

**Comment by CreativeMD** [comment] 2022-09-20 13:05
Somebody else posted the same issue on curseforge and it was caused by the `fadeVolume` and `fadePitch` setting being set to zero. Use the command /cmdclientconfig go to ambientsounds and hit the reset button next to these two options. Hit save and the issue should be solved. I'm not sure yet if a bug caused these config options to be zero.
