### ISSUE TITLE
1.20.1 forge sounds need setting change to restart

### ISSUE THREAD

**Issue by Techredd** [CreativeMD/AmbientSounds#227] opened 2024-05-22 20:54 UTC
As shown in https://www.youtube.com/watch?v=f8LrkIbzT4Q , if the debug says ambient sounds 
should be playing and they are not, then a sound setting needs to be changed to get them to restart. The ambient-reload command does not make them play again. A replicable way to get them to stop playing is to go underwater or fly up for a bit and come back.

1.20.1 forge 47.2.0, just ambient sounds v6.0.1 and creative core v2.11.28 installed through curseforge

**Comment by CreativeMD** [comment] 2024-05-25 09:19
Can you send me your log file? There must be going wrong for some reason.

**Comment by maxarq** [comment] 2024-06-03 07:53
i recorded playtest for you with abient sounds debug enabled.
https://youtu.be/78asYKUDNYE

**Comment by CreativeMD** [comment] 2024-06-11 18:28
Can you use the command /cmdclientconfig and set playSoundWithOffset to false and see if the issue still occurs?

**Comment by RionEV** [comment] 2024-06-15 17:00
Same issue, tried testing with playSoundWithOffset key set to false. Issue still occurs.

Don't know if it helps, but I'm doing some other testing, too - I use terralith, if that helps, but I'm noticing that Snowy Plains has no wind ambience, either.

Changing sound settings to prompt cave sounds to play, then returning to the surface in a silent biome fades out the cave sounds as expected.

Changing sound settings to prompt cave sounds to play, then returning to the surface in a forested biome fades between cave sounds and surface forest sounds as expected.

Standing still in a forested area seems to play sounds as expected.

Moving to a biome that is silent, then returning to one which is not silent, seems to cause the issue - but only if the sounds manage to fade out completely. If you return before the fade-out is complete, the volume level seems to return to normal, and the looping sounds continue. No events were logged during these tests.

Edit: Should clarify; I don't have debug logging enabled, just standard logging. Using AS6.0.1, Forge 47.3.1. Testing same again with debug enabled seems to demonstrate the same behaviour - new sounds aren't being played when added to the set of sounds that should be playing. As though perhaps they aren't sending the correct events? Strangely, [region:savanna][n:ambientsounds:animals.wolf] works correctly, regardless of this bug, even if I leave the area and return.

**Comment by RionEV** [comment] 2024-06-15 17:51
This issue seems to be a duplicate of #228; I'm just looking through the repo now and I'm finding that if something is marked in the config as
`"stream": true`
then it will not play unless prompted to by changing sound settings. Owl sounds and Wolf sounds play as expected in-game, and are not marked in the config as streamed. I can't see where this property is invoked in your code to offer suggestions and I don't know Git well enough to search for code specifically and not filenames in a repository, but from a brief look it does seem to have *something* to do with that configuration setting.

Edit: Just as a matter of due diligence, I noticed that Seagull sounds also had this property, went out to find a place where seagulls might be, and those sounds work just fine too.

**Comment by CreativeMD** [comment] 2024-06-16 13:32
Found the cause of the issue. A new version has been released which fixes the issue. Sorry for the trouble. Thanks for taking the time to report and troubleshoot this issue!

**Closed as completed by CreativeMD** 2024-06-16 13:32 UTC
