### ISSUE TITLE
Some sounds are played in the pause menu

### ISSUE THREAD

**Issue by Vinzound** [CreativeMD/AmbientSounds#195] opened 2023-10-08 23:34 UTC
What the title says, some ambient sounds continue to play when you pause the game.

I currently play on minecraft version 1.20.1.

**Comment by CreativeMD** [comment] 2023-10-24 12:09
Can you tell me which sounds? I tested it and could not reproduce it. Use the command /ambient-debug. Sorry for not responding earlier.

**Comment by Vinzound** [comment] 2023-11-05 23:16
Hello, I apologize for not responding soon too, I didn't think they would respond directly to me.

One of the sounds that is most often heard while in the pause menu is that of cicadas in the plains biomes, at the moment I think that is the only sound that I remember that there are problems with.

**Comment by CreativeMD** [comment] 2023-11-09 21:53
Fixed in the newest version. Thanks for reporting this issue!

Just so that you know: All sounds got paused, but ambientsounds continued to tick in the background and could start new sounds, which caused this issue.

**Closed as completed by CreativeMD** 2023-11-09 21:53 UTC
