### ISSUE TITLE
Rain sounds in the desert

### ISSUE THREAD

**Issue by Zergmazter** [CreativeMD/AmbientSounds#65] opened 2020-09-01 18:51 UTC
When it rains I hear rain sounds while in the desert. It cant rain in the desert in minecraft of course, but that doesnt stop the sounds. Just thought I'd let you know. Dont know if its on my end or your end.

**Comment by CreativeMD** [comment] 2020-09-04 08:28
Could not reproduce it using the newest version for 1.16.2. Can you type in /ambient-debug and send me a screenshot of it?

**Comment by Zergmazter** [comment] 2020-09-04 08:30
Oh darn I forgot to mention it was for 1.12.2.

**Comment by CreativeMD** [comment] 2020-09-04 08:31
That's fine I still support it just do the same thing and I will see what I can do.

**Comment by CreativeMD** [comment] 2020-09-17 13:41
Any news?

**Comment by CreativeMD** [comment] 2020-10-06 09:54
I will close this issue for now. If it still persists just reply here with the necessary information.

**Closed as completed by CreativeMD** 2020-10-06 09:54 UTC

**Comment by Zergmazter** [comment] 2020-10-07 00:46
Fixed! Sorry I've been working a lot of doubles.
