### ISSUE TITLE
Strange sound quality of ambientsounds [wind]

### ISSUE THREAD

**Issue by benten2000** [CreativeMD/AmbientSounds#100] opened 2021-11-04 15:37 UTC
I have an odd problem when using this mod in the recent mod pack release of FTB OceanBlock (which I have also reported on their GitHub issues page) but wanted to post one here as well just to be doubly safe.

The problem is with the latest AmbientSounds enabled in this pack so far only what I think is the wind.ogg sound effect that is playing for me in a terrible quality (sounds very compressed, tinny, slight robot effect while other sounds from the mod are perfectly fine)

Unsure if it's a mod conflict problem that is only affecting one sound file from the mod.
Managed to get a sample of the actual in-game audio of the problem.
[FTB.OceanBlock.-.Wind.audio.problem.zip](https://github.com/CreativeMD/AmbientSounds/files/7476087/FTB.OceanBlock.-.Wind.audio.problem.zip)

**Comment by CreativeMD** [comment] 2021-11-05 09:11
It does not really sound like bad quality but more like it's played twice at the same time. You can use the command /ambient-debug to see which sounds should currently be playing. Maybe there are two wind sounds for some reason? No idea if FTB OceanBlock changes the engine of AmbientSounds. Normally this should not happen. You could send me a screenshot while the issue is present and debug is enabled.

**Comment by benten2000** [comment] 2021-11-05 13:21
Ah a debug command, totally missed that option.
Here is a screenshot showing the debug information as requested.
![2021-11-05_13 20 18](https://user-images.githubusercontent.com/2871768/140516751-96dd4188-df33-43b8-8497-6e75dc519138.png)

**Comment by CreativeMD** [comment] 2021-11-05 14:57
Fixed in the newest version. Thanks for reporting this issue! Hope everything works fine now.

**Closed as completed by CreativeMD** 2021-11-05 14:57 UTC
