### ISSUE TITLE
Sound system crash still occurring with 2.0.4

### ISSUE THREAD

**Issue by Curunir** [CreativeMD/AmbientSounds#10] opened 2017-06-29 10:47 UTC
I have posted this to the long-running ticket, but apparently I do not have permissions to reopen it. So here is my issue:

I have been experiencing the crash issue as well on my private 1.10.2 pack. Upgrading to 2.0.4 made the sound system crashes much less frequent than they were with 2.0.2, but they still happen. There were other changes as well:

2.0.2
- only the sound system would crash and restart
- it would also display an fps count for some reason
- frequent occurence

2.0.4
- the entire client sometimes crashes now, right after it says it recovered from a sound system crash
- the line with the fps count is not displayed any more
- rare occurence, but not just once
- seems to happen only around machines, chiefly Thermal Expansion ones

Crash log from the latest one:
[crash-2017-06-29_12.36.32-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1111706/crash-2017-06-29_12.36.32-client.txt)

**Comment by agentdouble0** [comment] 2017-07-03 22:04
Same here, give it 15-30 minutes the sounds just stop, however for me I cannot pin point when it happens to me it's almost random. I doubt this will be fixed anytime soon but I hope for the best! Because I love this mod and don't care if its not perfect I will always use it ;-;

**Comment by agentdouble0** [comment] 2017-07-03 23:05
Oh and btw I'm using 2.0.4 for 1.11.2 and Forge 13.20.1.2386, sadly I have no logs for it if there anything I can test/do for you to help please let me know!

**Comment by CreativeMD** [comment] 2017-07-04 08:34
This a duplicate of this one: https://github.com/CreativeMD/AmbientSounds/issues/7

**Closed as completed by CreativeMD** 2017-07-04 08:34 UTC
