### ISSUE TITLE
sound system crash

### ISSUE THREAD

**Issue by 0Navis0** [CreativeMD/AmbientSounds#7] opened 2017-05-28 06:58 UTC
When I load a world, I get a message of the chat that the sound system crashed and try to restart it when the first chunks of the world load them. Then the game freezes and crashes, I get this crash report https://pastebin.com/ENRx0Sn7.

**Comment by CreativeMD** [comment] 2017-05-28 11:34
I could not reproduce this issue. So it's not caused by the forge version, FoamFix or any of my mods. It would be really hopefully if you could try to find out which mod causes this issue.

**Comment by Hypsellis** [comment] 2017-05-28 19:36
I noticed something else, all the Minecraft sounds are mute, and remove Ambient Sounds don't change anything. A mod seems to mess with Minecraft sounds, but I don't know which one, I try to find it.

**Comment by 0Navis0** [comment] 2017-05-28 21:19
Okay it seems the crash doesn't occur more, I don't know what caused it, anyway I close it for the time.

**Comment by 0Navis0** [comment] 2017-05-28 21:30
Okay the problem still happens sometimes >___<

**Comment by ghost** [comment] 2017-05-29 07:23
no it still happens, i will try to reproduce it with debugging mode. i hope it's foamfix.

**Comment by ghost** [comment] 2017-05-29 08:44
hello, i reproducet it on debugging mode. here is the crash report:
[crash-2017-05-29_11.41.52-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1035286/crash-2017-05-29_11.41.52-client.txt)
and here is the logs:
[fml-client-1.log.txt](https://github.com/CreativeMD/AmbientSounds/files/1035290/fml-client-1.log.txt)
[fml-client-latest.log.txt](https://github.com/CreativeMD/AmbientSounds/files/1035292/fml-client-latest.log.txt)
[latest.log.txt](https://github.com/CreativeMD/AmbientSounds/files/1035291/latest.log.txt)
hope these help. thanks.
BY THE WAY, what happened last time before sound system crash:
in-game music just stopped suddenly, i waited it to start again, but it didn't start, SS crashed.

**Comment by CreativeMD** [comment] 2017-05-29 12:16
Either you try to find the conflicting mod yourself or you can send me your mod and config folder so i can do it myself.

**Comment by ghost** [comment] 2017-05-29 15:57
https://www.technicpack.net/modpack/magenjia.1010676
Here is my modpack. Hope it helps... or tell me if i should find conflicting mod, but it will take years for me i think. But i can tell some mods that tweaks sound system:
Mxtune, dynamic surroundings, mobends

**Comment by 0Navis0** [comment] 2017-05-29 17:30
It is surely caused by Dynamic Surroundings, the problem doesn't seem to occur more without it.

**Comment by ghost** [comment] 2017-05-29 19:02
cool. hope it will be fixed.. @orecruncher may look it :D

**Comment by OreCruncher** [comment] 2017-05-29 19:54
Fix what?  A crashed sound system?  The stream handling thread in PauslCode (the underlying sound engine library) can crash, hard.  The logic in Dynamic Surroundings detects the dead thread in PaulsCode and automatically re-initializes the Minecraft sound engine.  IIRC there are some is a keyboard shortcut in Minecraft that can do this as well - just don't recall what it is.

You can turn this ability in Dynamic Surroundings OFF in the later BETA builds.  It will still give you a chat notification that the engine died.  The symptom of a dead sound engine is that no streaming sound will play.

**Comment by ghost** [comment] 2017-05-29 19:59
hey, i see something like "sound system crashed, restarting it..." on the chat JUST before this crash happens. what does it mean?

**Comment by OreCruncher** [comment] 2017-05-29 20:03
It means that Dynamic Surroundings detected that the streaming sound handling thread in PaulsCode died and it tells the Minecraft SoundManager to do a reloadSoundSystem().  I think it is the reload that is causing Ambient Sounds the problem.

**Comment by ghost** [comment] 2017-05-29 20:04
hmmm. but it's just a reload, if we disable it; shouldn't it be crash anyway?

**Comment by OreCruncher** [comment] 2017-05-29 20:05
The streaming thread will crash, Minecraft will not.

**Comment by ghost** [comment] 2017-05-29 20:08
hmmm... i see. so we can't disable sound system reloading feature in DS, right? 
in fact, instead of adding option to disable this feature, can't you improve it as doesn't cause this crash?
well, it's up to you, i'm just giving suggestion to help as much as i can to development of the mods :b

**Comment by ghost** [comment] 2017-05-29 20:09
so you know what u should do. i'm just a tester :D

**Comment by CreativeMD** [comment] 2017-05-29 20:09
I think this might be the issue here. Is there an event or something like that?

**Comment by OreCruncher** [comment] 2017-05-29 20:09
No, you CAN disable the auto-reload feature of Dynamic Surroundings.  Option should be in the latest BETA.  It will still give you a chat message indicating that the thread died so you can restart the client.

**Comment by OreCruncher** [comment] 2017-05-29 20:10
Forge posts a SoundLoadEvent as the last thing it does in the reloadSoundSystem().

**Comment by CreativeMD** [comment] 2017-05-29 20:16
Thanks for quick help, this should fix it:
https://www.dropbox.com/s/tbap8ieg0jkzfzs/AmbientSounds%20v2.0.2%20mc1.11.2.zip?dl=1

Will release once it's confirmed.

**Comment by ghost** [comment] 2017-05-29 20:17
oh... how fast... thank you creativemd, and thank you orecruncher. i'm very happy now to use both mods with no pain :d

**Comment by CreativeMD** [comment] 2017-05-29 20:23
@OreCruncher pretty cool idea, since the sound system crashes rather often.

**Comment by OreCruncher** [comment] 2017-05-29 20:25
lol - yeah.  Since 1.7.10 I been wondering why my streaming sounds just stopped for no apparent reason.  I eventually caught it in a debugger, spent 5 minutes cursing, then went about "fixing" it.

**Comment by ghost** [comment] 2017-05-29 20:27
by the way, i just wanted to mention my second comment on this issue (https://github.com/CreativeMD/AmbientSounds/issues/7#issuecomment-304607633) 
it(ingame music stops suddenly sometimes) was happening for a too long time before, i can't even remember.
edit: so, it was a sound system crash in ambient sounds, as i understood. so i just wanted to ask it, shouldn't it be fixed as an issue?

**Comment by CreativeMD** [comment] 2017-05-29 20:38
But also the SoundManger causes a lot of issues. It uses a HashBiMap so there are two connected maps which contain all sounds (HashMap<String,ISound> and reversed HashMap<ISound,String). The problem is that they will not be synchronized immediately. So if you play a sound and check one tick later if it is playing or not it will (most likely) return false.
There used to be a bug in the old AmbientSounds that if you would leave a biome and enter it again within a few seconds, games with low fps crashed, since the sound was still in the second hashmap (throwing a duplicate exception). It took me until now to find out what is causing this issue, so i just write my own soundmanager :D

**Comment by ghost** [comment] 2017-05-29 21:10
sounds amazing :D get luck with

**Comment by 0Navis0** [comment] 2017-05-29 21:13
I get another crash with the new version https://pastebin.com/bG7RUh3N

**Comment by CreativeMD** [comment] 2017-05-29 21:38
Could you try to redownload it (it should be fixed now).

**Comment by 0Navis0** [comment] 2017-05-29 22:17
It still doesn't work. :(

**Comment by CreativeMD** [comment] 2017-05-29 22:44
Same crash?

**Comment by 0Navis0** [comment] 2017-05-30 00:44
Yes :(

**Comment by ghost** [comment] 2017-05-30 18:47
hey ah, i just disabled sound system reload feature in DS as @OreCruncher said, then i played about 1 hour; and sound system has been crashed about 20 times, and at the last; minecraft crashed. :(

**Comment by CreativeMD** [comment] 2017-05-30 19:52
I could not reproduce this issue with only AmbientSounds and DS installed using AmbientSounds v2.0.2, no idea why it crashes for you, i will now try to download to modpack and to some testing with all the other mods installed as well.

**Comment by ghost** [comment] 2017-05-30 19:57
hmm, you can download my [modpack](https://www.technicpack.net/modpack/magenjia.1010676) if you want, sound system reload feature disabled in the latest version. thanks a lot. hope it be fixed :(

**Comment by OreCruncher** [comment] 2017-05-30 21:48
I would try it with kenijey's pack.  In my experience the sound system crash is related to client lag, and some modpacks are worse than others.

**Comment by CreativeMD** [comment] 2017-05-31 09:54
Ok i did some testing, running the game with decent 15 FPS, but no crash or what so ever. This version will fix the crash, but since i don't really know what is causing this issue. So AmbientSounds might be quiet once it will happen again:
https://www.dropbox.com/s/tbap8ieg0jkzfzs/AmbientSounds%20v2.0.2%20mc1.11.2.zip?dl=1

**Comment by ghost** [comment] 2017-05-31 13:15
hope it fixes it... thanks.

**Comment by 0Navis0** [comment] 2017-05-31 23:26
The crash still occurs for me. :( https://pastebin.com/Gc1MWD6W

**Comment by CreativeMD** [comment] 2017-06-01 09:15
@Hypsellis you are crash are really weird and don't make sense at all. When does it happen? During loading the world? Randomly while playing?

**Comment by ghost** [comment] 2017-06-01 18:41
hey everyone, ah; i dedicated the crash. mxTune mod causes this shit. i deleted it, no sound system crashes anymore. just wanted to let you know

**Comment by 0Navis0** [comment] 2017-06-01 21:35
For me it's not caused by MxTunes since I never downloaded it. I haven't any ideas what cause it, anyway it happens randomly while playing.

**Comment by CreativeMD** [comment] 2017-06-02 10:29
Actually only a thread could cause issues like that, but it is not threaded. As i said already, that crash doesn't make any sense, but maybe this version fixes it:
https://www.dropbox.com/s/hlyz5o7jei4hzti/AmbientSounds%20v2.0.3%20mc1.11.2.zip?dl=1
It would be really helpful if you could take a look at the log afterwards and see if AmbientSounds is logging anything suspicious.

**Comment by ghost** [comment] 2017-06-02 19:42
ahhhhh, yes; it crashed again without mxTune too. i really don't understand what's going on, but it crashed without ambinet sounds too. dunno what causes...

**Comment by ghost** [comment] 2017-06-02 19:42
but, it crashed after playing 6 hours.

**Comment by CreativeMD** [comment] 2017-06-02 19:56
crash-report? using v2.0.3?

**Comment by ghost** [comment] 2017-06-02 19:59
i just installed it, i will when it crashed. thanks.

**Comment by 0Navis0** [comment] 2017-06-03 00:37
It seems to work now, I don't get more crash.

**Comment by 0Navis0** [comment] 2017-06-03 03:41
Damn I still get the same crash. :(

**Comment by CreativeMD** [comment] 2017-06-03 09:40
This cannot be the same crash, could please send me the log every time? Since i have updated the code, at least the line number should change, furthermore i have implement a non null check, so you should see something in the log. So it would be really good if you could provide me your whole log.

**Comment by 0Navis0** [comment] 2017-06-03 12:02
Here is the crash report. https://pastebin.com/wwQE54i2

**Comment by CreativeMD** [comment] 2017-06-03 12:08
Ok ... could one of you test this issue with only AmbientSounds installed. It would be very helpful to know if this is an issue caused by a mod or not. As I said before this crash is actually impossible to happen without threads.

**Comment by ghost** [comment] 2017-06-03 12:17
as i said, it will take years to find which mod causes :D because it happens very random.

**Comment by ghost** [comment] 2017-06-03 12:24
hey ah, here is another crash with 2.0.3 AS
[crash-2017-06-03_15.22.43-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1049590/crash-2017-06-03_15.22.43-client.txt)

**Comment by ghost** [comment] 2017-06-03 12:24
and what is paulscode in the crash?

**Comment by ghost** [comment] 2017-06-03 12:27
hey @Hypsellis , which mods you are using?

**Comment by OreCruncher** [comment] 2017-06-03 12:58
@kenijey PaulsCode is the underlying sound engine in Minecraft.

**Comment by ghost** [comment] 2017-06-03 13:04
oh sry i remember it now
i saw it before on eclipse in forge directory

**Comment by 0Navis0** [comment] 2017-06-03 13:56
I use so many mods in same time, it would take a lot of time before to know which one specifically cause this crash. :(

**Comment by CreativeMD** [comment] 2017-06-03 13:57
Just run it without any other mods, i just need to know if a mod is causing it or not.

**Comment by 0Navis0** [comment] 2017-06-03 14:10
It doesn't crash without other mods.

**Comment by OreCruncher** [comment] 2017-06-03 14:25
@CreativeMD Does your sound engine run in the client thread, or separate thread?

**Comment by CreativeMD** [comment] 2017-06-03 14:32
Client thread, i'm using the tick event:
https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/TickHandler.java#L192

**Comment by OreCruncher** [comment] 2017-06-03 14:38
OK.  A possibility is that if you are listening for the SoundLoadEvent the underlying sound system may not be fully initialized.  loadSoundSystem() spins off a thread to the init, and that routine is what creates the various threads in PaulsCode.  (PauslCode does a lot of init in it's SoundSystem CTOR which generally is not good OOP practice.)  Anyways, you may want to check the "isLoaded" flag of the Minecraft SoundManager, ~~or at the top of your tick() routine check that system is not null~~.  This may solve it for you.

**Comment by CreativeMD** [comment] 2017-06-03 14:46
Thanks, but this solves the AmbientSoundEngine crash, but actually it's about the TickHandler what is crashing without any particular reason.

**Comment by OreCruncher** [comment] 2017-06-03 14:51
[You mean this one](https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/TickHandler.java#L199) from Hypsellis's report?

EDIT: If it is, then I recommended looking at your world unload handler.  Make sure you are checking whether it is remote or not.  My theory is that the server thread is unloading a world, the handler gets invoked, which in turn yanks the "situation" out from under the client thread.

**Comment by CreativeMD** [comment] 2017-06-03 15:07
Oh good idea, that might causes this issue, especially if you have dimensional mods installed. Hopefully it will work now:
https://www.dropbox.com/s/hlyz5o7jei4hzti/AmbientSounds%20v2.0.3%20mc1.11.2.zip?dl=1

**Comment by ghost** [comment] 2017-06-03 15:09
what if sound system crashes (only ss, not mc) without ambient sounds? :D  (very rare)

**Comment by OreCruncher** [comment] 2017-06-03 15:20
Generally mods don't notice.  If this sound system crash were to occur the only thing a player will notice is that streaming sounds (like music) will stop playing.  Mods like Dynamic Surroundings have many more streaming sounds and it becomes noticeable.  The reason I put this restart in was because players were starting to point the finger at DS for the problem when the reality was that PaulsCode is pretty fragile and does not handle IO errors gracefully.

**Comment by CreativeMD** [comment] 2017-06-03 15:21
Yes indeed, it was also a problem of AmbientSounds too, maybe some asm transforming could fix it? I might take a look into that.

**Comment by OreCruncher** [comment] 2017-06-03 15:29
Would be nice if you could work it out.  Other possibility is to wrap the underlying URL stream so it detects error conditions and closes off the stream cleanly.  This may cause PaulsCode to choke if an OGG stream reaches EOS when it is expecting more data - but it would be interesting to see what happens.

**Comment by OreCruncher** [comment] 2017-06-03 18:35
@Hypsellis @kenijey Could you try out a test Dynamic Surroundings located [here](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.5.3TEST1)?  It has some prototype code that does the following:

+ Caches sounds that are < 64K in length.  This is to improve overall handling of frequently played small sound clips.
+ Wraps the sound resource from the JAR so that if there is an error it attempts graceful handling.

@CreativeMD If you want to take a look at the code you can find that [here](https://github.com/OreCruncher/DynamicSurroundings/tree/v3.4.5.3TEST1/src/main/java/org/blockartistry/lib/sound).  I use ASM to hook the SoundManager.getURLForSoundResource and redirect it to my own implementation in SoundCache.getURLForSoundResource.

**Comment by 0Navis0** [comment] 2017-06-03 21:47
It seems I don't get more the crash, at least for the time. I noticed another minor issue. Underground sounds play them when the sky is partially covered by blocks, I suppose the sound event depends of the level of natural light. The problem is the underground sounds play them in huge forest with many trees covering the the sky, typically some BOP biomes.

**Comment by 0Navis0** [comment] 2017-06-03 21:55
Okay I just got the crash again, but this time it's sighly different, it looks like the first ones I got. It crashed just after the sound system crash and try to restart. https://pastebin.com/bqBDmVrh

**Comment by OreCruncher** [comment] 2017-06-03 22:43
@Hypsellis Have you tried it with the Dynamic Surroundings v3.4.5.3 Test version?  The crash indicates you were using the v3.4.5.2 version.

**Comment by 0Navis0** [comment] 2017-06-03 22:50
No I didn't try it yet, I'm currently trying it now.

**Comment by 0Navis0** [comment] 2017-06-03 23:26
I didn't get crash yet with this version, I don't know if the problem is solved.

**Comment by 0Navis0** [comment] 2017-06-05 14:12
I just got a crash again, but this time it toke many time before it crashes, it seems to happen rarely now. It seems the crash happens when I move quickly between biomes and the sounds change, the sounds system crashes and tries to restart, and then Minecraft crashes. https://pastebin.com/t6AmNR4B

**Comment by ghost** [comment] 2017-06-05 14:12
this crash happens without ambient sounds too. yes, it's very rare and i couldn't find which mod causes.

**Comment by CreativeMD** [comment] 2017-06-05 14:41
Okay, sorry that i couldn't respond the last 2 days, but now i will try to fix it.

**The situation**
The paulscode engine crashes randomly, while trying to play a streaming sounds. DS has implemented a feature which reloads the engine once it has crashed. AmbientSounds is not prepared for it, meaning crashes can occur during reloading the sound engine. Although they are rather unlikely if you play for a while it will eventually happen (as far as i can tell).

**Ways to solve this**
* I could prepare AmbientSounds to be aware of reloading the sound engine at any point
* I could try to fix the bug which causes the engine to crash in the first place.

**What i'm trying**
So i tried to fix the crash of the paulscode engine. The new version of AmbientSounds released on curseforge could do so, but unfortunately it is not tested as i couldn't reproduce the crash of the engine. It would be very helpful if you could test it out for me. @OreCruncher Does DS log the crash of the sound engine (it would help to see if it is fixed or not)? If the game crashes or all sounds stop (engine crashes), please also provide the full log of your game.

@OreCruncher
AmbientSounds overwrites the OggDecoder with a "fixed" version of it. Actually i just add a try and catch to the `readBytes()` method as the decoder seems to be implemented correctly (following the tutorials of the JCraft website): https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/CodecJOrbisFixed.java#L623

If the issue is more complicated to solve, i will prepare AmbientSounds to not crash if the DS is reloading the engine.

**Comment by OreCruncher** [comment] 2017-06-05 15:15
@CreativeMD Yes, warning information is put into  the client log file when the sound engine gets restarted.  Look for the text "It looks like the sound system has crashed".  As for the fix I am not too familiar with the code.  One thing that I do wonder about is whether you need to set end of stream to TRUE and cause the entire sound play to be aborted.

**Comment by CreativeMD** [comment] 2017-06-05 16:00
@OreCruncher oh yes, might be a good idea to add this as well, but first i will wait if this fix causes anything else to crash.

**Comment by CreativeMD** [comment] 2017-06-06 12:47
Any crashes so far? Has someone tested it already?

**Comment by ghost** [comment] 2017-06-06 13:22
I abandoned my modpack. I will build a new modpack in 1.12. We will test it together :) so don't forget to update your mods when forge released, creativemd :D

**Comment by tyra314** [comment] 2017-06-07 16:37
I got a crash with the latest versions of AmbientSound and DynamicSurroundings from Curse, v2.0.3 and 3.4.5.3 respectively. 
I also have SoundFilters-0.9 in the pack, which could mess with the sound system.

Forge: 13.20.0.2314 (on both server and client)
Right now, I'm playing on a server, but at least the sound engine also crashed in single player.

https://gist.github.com/tyra314/9f73e4c958cea26ea370c9390964ba4c

**Comment by CreativeMD** [comment] 2017-06-07 18:02
Could you please send me your complete log file? It allows me to find out whether the sound engine crashed or not.

**Comment by tyra314** [comment] 2017-06-07 21:01
Sorry, it's already gone. I'll make sure to send you both next time it happens.
But I could see the chat text about restarted sound engine and a second later my whole client crashed.

**Comment by 0Navis0** [comment] 2017-06-08 02:56
I got this crash with the last Ambient Sounds and Dynamic Surroundings versions. https://pastebin.com/TTGysJMW

**Comment by CreativeMD** [comment] 2017-06-08 09:08
Please i need the whole log, which can be found in the logs folder. The old once will be archived so you should be able to find those too. I need those logs otherwise i can't find out why the engine has crashed. The crash-reports don't really matter at the moment.

**Comment by 0Navis0** [comment] 2017-06-08 16:08
I don't have it more, I will give you it when I will get the crash again.

**Comment by tyra314** [comment] 2017-06-08 18:39
It just happend once more. Here a gist with both, crash report and log file:

https://gist.github.com/tyra314/209e9ecef27e43d325e103708af5242d

**Comment by CreativeMD** [comment] 2017-06-09 09:12
Is it the full log file? Because it does not even cover the whole startup process :(

**Comment by 0Navis0** [comment] 2017-06-09 15:34
It's not the good log, I will post it when I will get the crash again.

**Comment by OreCruncher** [comment] 2017-06-17 15:10
@CreativeMD I did manage to catch the crash in a debugger.  Here is a snip of the stack trace of what I saw:
```
[14:23:00] [Thread-26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[14:23:00] [Thread-26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.codecs.CodecJOrbis.readBytes(CodecJOrbis.java:587)
[14:23:00] [Thread-26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.codecs.CodecJOrbis.read(CodecJOrbis.java:356)
[14:23:00] [Thread-26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.Source.stream(Source.java:953)
[14:23:00] [Thread-26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
```
The null pointer it is referring to is the codec for the sound stream.  It is null.  What I saw in the debugger was that the IO stream for the sound resource was *closed* when PaulsCode was trying to read it.  The null pointer and the closed stream tells me that something in PaulsCode closed out the sound source (closed the stream and disposed of the codec) out from underneath the stream thread.  I think the best that can be achieved given this circumstance is to make sure the thread doesn't die and the offending sound source is removed from the internal lists to make sure it doesn't trip over it again.

**Comment by CreativeMD** [comment] 2017-06-19 12:48
@OreCruncher It looks like this a weird threading issue, since i had a different crash before.

Did the sound engine crash afterwards? I'm printing the exception just for debugging purpose, theoretically the engine could have survived it: https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/CodecJOrbisFixed.java#L624

Have you used the newest version (v2.0.4)?

**Comment by OreCruncher** [comment] 2017-06-19 12:58
@CreativeMD Ah, no.   This is with just my mod.  I been trying like the dickens to figure out the root cause of why the thread is crashing and managed to collect more data.  It's more than I had before; not sure of all the details you have discovered. I am feeling more comfortable that this is a bug with PaulsCode, and the reason it is showing up is because the number of streaming sounds that are being played increases the chance it will be seen.

It also gives me a bit more confidence in the "just trap the error and suppress" approach.  It seems that some other thread already performed house cleaning on the sound source state so trying to do extensive cleanup with your patch may not be required.

**Comment by CreativeMD** [comment] 2017-06-19 13:39
@OreCruncher ok, but your crash is still really weird. Have you used 1.11.2? Since there can't be a nullpointerexception at this line in 1.11.2.

Actually i don't know too much about this issue. I only knew of its existence before and also reported it to the author (http://www.paulscode.com/forum/index.php?topic=14927.msg29451#msg29451). As you can see it's a different crash:

```[17:36:04] [Thread-11/INFO]: [STDERR]: java.lang.NullPointerException
[17:36:04] [Thread-11/INFO]: [STDERR]: 	at com.jcraft.jogg.StreamState.packetout(StreamState.java:186)
[17:36:04] [Thread-11/INFO]: [STDERR]: 	at paulscode.sound.codecs.CodecJOrbis.readBytes(CodecJOrbis.java:575)
[17:36:04] [Thread-11/INFO]: [STDERR]: 	at paulscode.sound.codecs.CodecJOrbis.read(CodecJOrbis.java:354)
[17:36:04] [Thread-11/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:953)
[17:36:04] [Thread-11/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
```

It might be a good idea to contact him again, especially if you have collected more information about this issue.

**Comment by OreCruncher** [comment] 2017-06-19 13:49
@CreativeMD It is possible my stack is a bit different.  Reasons:

* [I have a sound cache](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/lib/sound/SoundCache.java).  What this cache does is keep OGG sounds < 64K in memory.  When a URL is needed for an OGG I look it up in the cache and reuse the data.  Underneath it all is a ByteArrayInputStream.
* For a stream >=64K [I wrap the IO stream](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/lib/sound/SoundInputStream.java) provided by the resource manager in order to trap streaming errors.  When doing my testing I have breakpoints set in this wrapper and the callstack above is from one of those breakpoints.  My hope was that the wrapper would prevent the error, but unfortunately the masking caused it to trigger something further down the line.

From what I can see Minecraft is not using the latest version of PaulsCode.  I wonder if there is an updated codec that can be installed and used with the installed version.

**Comment by CreativeMD** [comment] 2017-06-19 15:08
@OreCruncher okay, i have contacted the author again, maybe he can help us out:
http://www.paulscode.com/forum/index.php?topic=14927.msg30042#msg30042

**Comment by CreativeMD** [comment] 2017-06-21 08:12
@OreCruncher The newest AmbientSounds version should end the stream properly, so the sound engine shouldn't crash anymore.

I looked deeper into the code and my guess is, this crash occurs while cleaning up the coded. Either because the engine tries to play a new sound or it cleans up the codec too early. The first case sounds more promising.

**My guess**
If the engine runs out of streaming channels, it uses an already existing channel to play the new stream (and stops the old one). Maybe those threads are not in sync and therefore will eventually collide. Before the new stream will be played it will clean up everything, if the other thread is streaming at exactly this moment, this crash could occur. It's just an idea, but i will implement some logging, so i might be able to find out if that's the issue or not.

**The fixed codec**
It might be a good idea if you could use this fixed codec, too. Feel free to use and add it to your repository: https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/CodecJOrbisFixed.java

**Comment by ghost** [comment] 2017-06-21 09:00
uhm, we are playing it on 1.12 for a week, and no any sound system crash so far. (using AS 2.0.4)

**Comment by CreativeMD** [comment] 2017-06-23 21:02
If it happens again with (v2.0.4) just reopen this issue, for now i call it fixed ... finally. @OreCruncher thanks for your kind help, you really helped me a lot and also thanks for reporting this issue. I hope everything works fine now.

**Comment by Curunir** [comment] 2017-06-29 10:43
I have been experiencing the crash issue as well on my private 1.10.2 pack. Upgrading to 2.0.4 made the sound system crashes much less frequent than they were with 2.0.2, but they still happen. There were other changes as well:
2.0.2
- only the sound system would crash and restart
- it would also display an fps count for some reason
- frequent occurence

2.0.4
- the entire client sometimes crashes now, right after it says it recovered from a sound system crash
- the line with the fps count is not displayed any more
- rare occurence, but not just once
- seems to happen only around machines, chiefly Thermal Expansion ones

Crash log from the latest one:
[crash-2017-06-29_12.36.32-client.txt](https://github.com/CreativeMD/AmbientSounds/files/1111694/crash-2017-06-29_12.36.32-client.txt)

**Comment by CreativeMD** [comment] 2017-06-29 10:49
Could you send me your complete log file? I need to know why the sound engine crashes.

**Comment by OreCruncher** [comment] 2017-06-29 12:42
It is DS that is printing out the FPS debug information.  I was trying to gather some data points about the problem.  The latest version does not print this info as it is no longer needed.

**Comment by Curunir** [comment] 2017-06-29 15:10
I found a reference to the crash in the attached log. Zipped it for you, since it's ~9MiB as-is.
[fml-client-3.zip](https://github.com/CreativeMD/AmbientSounds/files/1112503/fml-client-3.zip)
Thanks for looking into it.

I should mention that I have combined AmbientSounds with DynamicSurroundings and SoundFilters in this fashion before. The crashes only started with version 2.0.

**Comment by CreativeMD** [comment] 2017-06-29 16:05
Thanks a lot!!! Finally i can take a look at the crash itself ...

```
[12:35:48] [Thread-23/INFO] [STDERR/]: [com.creativemd.ambientsounds.CodecJOrbisFixed:readBytes:626]: java.lang.NullPointerException
[12:35:48] [Thread-23/INFO] [STDERR/]: [com.creativemd.ambientsounds.CodecJOrbisFixed:readBytes:626]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.readBytes(CodecJOrbisFixed.java:587)
[12:35:48] [Thread-23/INFO] [STDERR/]: [com.creativemd.ambientsounds.CodecJOrbisFixed:readBytes:626]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.read(CodecJOrbisFixed.java:356)
[12:35:48] [Thread-23/INFO] [STDERR/]: [com.creativemd.ambientsounds.CodecJOrbisFixed:readBytes:626]: 	at paulscode.sound.Source.stream(Source.java:953)
[12:35:48] [Thread-23/INFO] [STDERR/]: [com.creativemd.ambientsounds.CodecJOrbisFixed:readBytes:626]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[12:35:48] [Thread-23/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[12:35:48] [Thread-23/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.Source.stream(Source.java:962)
[12:35:48] [Thread-23/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[12:36:16] [Client thread/INFO] [TabbyChat2/]: [CHAT] It looks like the sound system has crashed.
[12:36:16] [Client thread/INFO] [TabbyChat2/]: [CHAT] Attempting to restart...
[12:36:16] [Client thread/WARN] [dsurround/]: It looks like the sound system has crashed.
[12:36:16] [Client thread/WARN] [dsurround/]: Attempting to restart...
[12:36:22] [Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@2e58a162:
java.lang.NullPointerException
	at paulscode.sound.SoundSystem.stop(SoundSystem.java:1188) ~[SoundSystem.class:?]
	at com.creativemd.ambientsounds.AmbientSoundEngine.stop(AmbientSoundEngine.java:241) ~[AmbientSoundEngine.class:?]
	at com.creativemd.ambientsounds.AmbientSound.stopSound(AmbientSound.java:220) ~[AmbientSound.class:?]
	~SNIP~
```

After some further investigation i found that the source will be cleaned up while it is streaming, which can only happen if the sound is removed by another thread without synchronization (as far as i can tell).

AmbientSounds does something similar, so I fixed it, although i'm still not really sure if this is the real cause of this issue, since it only removes sources which have stopped playing (besides the fact that this issue also appears if my mod isn't installed).

That's why I have contacted the author of the paulscode engine as well to see if it might be an issue of the engine itself.

Anyway, could you test this version and see if it happens again?
1.11.2: https://www.dropbox.com/s/cscwmyey3d63ebl/AmbientSounds%20v2.0.5%20mc1.11.2%20%26%201.12.zip?dl=1
1.10.2: https://www.dropbox.com/s/o60rkfqlf41v2n5/AmbientSounds%20v2.0.5%20mc1.10.2.jar?dl=1

**Comment by Curunir** [comment] 2017-06-29 17:19
I will test it. However, I only have a 1.10.2 pack ready, and since this bug seems to occur infrequently now, it might take a while before I can give any results -  unless it crashes again. Let's hope for the best.

Update: It did crash again, rather quickly. But this time it was only the sound system again, not the entire client. Look at timestamp 19:27:43 in the attached log, and some seconds prior.
I am getting the impression it always happens when I am actively doing something. Maybe it is triggered by adding some player sound on top of other sounds already being played. I am flying around with a jetpack a lot, might be related to that - although I am just speculating here.
[fml-client-latest.zip](https://github.com/CreativeMD/AmbientSounds/files/1112967/fml-client-latest.zip)

**Comment by CreativeMD** [comment] 2017-06-29 18:02
Oh nice, the author of the paulscode engine replied as well. It looks like this is an issue of the engine itself. Hope there is a way to fix it.

Thanks again for all your help.

**Comment by Curunir** [comment] 2017-07-09 16:46
I don't mean to badger anybody, but what is the status on this? Running with that unreleased 2.0.5 build ever since. It still does occasionally crash the sound system, but the client always recovers from that (after a 2-3 second hard freeze).

**Comment by CreativeMD** [comment] 2017-07-10 09:15
It all depends on the author of the paulscode engine now, since there is nothing i could do on my end. Actually he abandoned this project already, but now he takes a look at it again and see if he can fixes it. If there are any news, i will post it here.

**Comment by CreativeMD** [comment] 2017-10-19 10:58
It's been a while and the author of the sound engine still hasn't fixed it, so i decided to fix this issue on my own. It's a bit hacky but i hope it does what it is supposed to do.

So could you test this pre-release and see if this crash still occurs or not? I tested it myself and it works fine so far:
1.11.2: https://www.dropbox.com/s/23w7zfw5ytj17k1/AmbientSounds%20v2.1.0%20mc1.11.2.jar?dl=1
1.12.2: https://www.dropbox.com/s/7ipsg7btl0uwxao/AmbientSounds%20v2.1.0%20mc1.12.2.jar?dl=1

**Comment by OreCruncher** [comment] 2017-10-19 11:18
@CreativeMD If this works out could you release it as a separate mod as well?

**Comment by ghost** [comment] 2017-10-19 11:33
all i understood from this sound system crash thing is: paul's code sux xD

**Comment by OreCruncher** [comment] 2017-10-19 13:23
Actually the code isn't that bad.  Some of the more challenging bugs to find are concurrency related.  This particular one is *very* rare where vanilla Minecraft is concerned.  Only reason that it crops up with DS and Ambient Sounds is that both our mods makes heavy use of sound streaming.

**Comment by ghost** [comment] 2017-10-19 13:30
it's why i'm extremely too hopeful from 1.13

**Comment by CreativeMD** [comment] 2017-10-20 09:44
Furthermore he already abandoned this project. I'm quite happy that he even replied and helped me to find out what the issue is. He said he will try to fix it on his own if he has enough time, but it looks like he is just too busy, that's why i did it myself.

@OreCruncher i was thinking of adding it to CreativeCore, but my goal is to merge it into Forge anyway. So i don't think a separate mod would be a good idea. If you want to i can show you how i fixed it so you can implement it in DS as well (till it will be merged into Forge).

**Comment by CreativeMD** [comment] 2017-10-23 11:37
Ok, i guess it is fixed now. Fix will be able for 1.12.2, 1.11.2 and 1.10.2.

@OreCruncher feel free to contact me anywhere (discord might be the best) so you can add this fix to DS as well, otherwise you will have to wait till it is merged into Forge. Hopefully i will manage to create a pr the next days.

**Closed as completed by CreativeMD** 2017-10-23 11:37 UTC

**Comment by ghost** [comment] 2017-10-23 11:40
hey creativeMD, did you fix it only at your side or a little bit globally?
answer is a bit globally

**Comment by CreativeMD** [comment] 2017-10-23 11:44
If this issue still occurs just let me know and send me the crash report.

**Comment by ghost** [comment] 2017-10-23 11:50
ok. :D

**Comment by ghost** [comment] 2017-10-23 12:45
wow, it is ammazzing. i really forced it to cause crash but nope. it works good.
you can even try [my extra heavy modpack](https://github.com/kenijey/Ezteria) to see it, that includes ambient sounds, DS and weather2(Weather, Storms & Tornadoes) mods. it works fine :D

**Comment by SimulatorSia** [comment] 2017-12-30 08:51
you guys all had Creative Core installed and whenever I have it installed it happens to me too. Perhaps CreativeCore is causing the crash with Dynamic surroundings or Ambient Sounds

**Comment by CreativeMD** [comment] 2017-12-30 11:18
This crash should be fixed already, in the newer versions of AmbientSounds. If this still occurs to you please provide a log file and a list of all your mods installed (including forge version).

**Comment by SimulatorSia** [comment] 2018-01-01 11:32
I found out it's not with Ambient Sounds, it's with Dynamic Surroundings, and it's because of Aether Legacy's music overlapping the Dynamic Sounds, it happens still when I take AmbientSounds out of the mods folder

**Comment by OreCruncher** [comment] 2018-01-01 17:49
This the sound engine crash?  I am finishing up a build that contains the patch that CreativeMD made.  The current posted Dynamic Surroundings mod still has the auto restart.
