### ISSUE TITLE
[1.18.1] Wrong sound plays in "minecraft: snowy_plains" in LAN multiplayer.

### ISSUE THREAD

**Issue by quenra** [CreativeMD/AmbientSounds#115] opened 2021-12-26 17:19 UTC
In weather /weather thunder, ambient sounds of rain and thunderstorms work in the winter biome, when the sounds of a howling blizzard and falling snow should play. Screenshot attached 
![2021-12-26_19 15 12](https://user-images.githubusercontent.com/96695092/147415478-611adcf2-1ef1-4679-bbd5-20fa8b170b6e.png)

**Comment by CreativeMD** [comment] 2021-12-28 22:08
Can you use the command /ambient-debug and make another screenshot? (Could not reproduce this issue)

**Comment by quenra** [comment] 2021-12-31 11:22
Yea, sure. Its works good now idk what i've done
![2021-12-31_13 22 53](https://user-images.githubusercontent.com/96695092/147820744-e1d749ac-881b-490d-8772-abebcebe950c.png)
![2021-12-31_13 23 00](https://user-images.githubusercontent.com/96695092/147820745-688978c5-9185-4589-a581-500721dc8d83.png)

**Comment by CreativeMD** [comment] 2022-01-03 10:52
I don't see any issue? I can't see any inappropriate sounds.

**Comment by CreativeMD** [comment] 2022-01-08 09:00
Will close this issue for now. If it's still there reply here.

**Closed as completed by CreativeMD** 2022-01-08 09:00 UTC
