### ISSUE TITLE
Sound inside buildings and cellar

### ISSUE THREAD

**Issue by TheRealDadbeard** [CreativeMD/AmbientSounds#125] opened 2022-02-20 19:29 UTC
Hy,

I addes some screenshot of what kind of sounds and where they happen. I am on 5.0.9 Ambient Sound and creative core 2.5.0
![2022-02-20_20 24 37](https://user-images.githubusercontent.com/23340600/154860584-fcd81492-c041-46f5-90c3-f744c7d7739a.png)
![2022-02-20_20 24 58](https://user-images.githubusercontent.com/23340600/154860588-8f92df5a-4edf-4b30-98b1-30d980f8ab52.png)

**Comment by CreativeMD** [comment] 2022-03-11 15:13
Fixed in the newest version. The problem is that doors were not considered solid. If you are still unhappy with the result of the newer version post it here.

**Closed as completed by CreativeMD** 2022-03-11 15:13 UTC
