### ISSUE TITLE
Music Discs do not play until sounds settings touched

### ISSUE THREAD

**Issue by Fiopon** [CreativeMD/AmbientSounds#229] opened 2024-06-04 17:03 UTC
https://github.com/CreativeMD/AmbientSounds/assets/56209751/845fefdd-0164-4b55-83df-4c9c4d226d1a

**Comment by CreativeMD** [comment] 2024-06-08 09:30
Thanks for reporting. Seems like a duplicate of: https://github.com/CreativeMD/AmbientSounds/issues/227 

Will the close the issue here and respond in the author issue.

**Closed as completed by CreativeMD** 2024-06-08 09:30 UTC
