### ISSUE TITLE
1.12 Audio Hang

### ISSUE THREAD

**Issue by ghost** [CreativeMD/AmbientSounds#12] opened 2017-07-20 05:05 UTC
Minecraft 1.12
forge 14.21.1.2387

This has been happening every now and then, figured I'd post something about it. From lazily analyzing it, seems an audio track seems to bug and keep playing and never stops, resource reload [F3+T] works, but it will eventually happen again. Three noticeable tracks that hang are 'underwater', 'rain', and 'cricket' [night? i think].

There maybe few similar errors that slipped past me in logs, but again, I'd post at least something.

```
[21:13:28] [Thread-7/INFO]: [STDERR]: java.lang.NullPointerException
[21:13:28] [Thread-7/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.readBytes(CodecJOrbisFixed.java:587)
[21:13:28] [Thread-7/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.read(CodecJOrbisFixed.java:358)
[21:13:28] [Thread-7/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:953)
[21:13:28] [Thread-7/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[21:14:52] [Thread-7/INFO]: [STDERR]: java.lang.NullPointerException
[21:14:52] [Thread-7/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.readBytes(CodecJOrbisFixed.java:587)
[21:14:52] [Thread-7/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.read(CodecJOrbisFixed.java:358)
[21:14:52] [Thread-7/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:953)
[21:14:52] [Thread-7/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
```
and
```
[21:45:18] [Thread-6/INFO]: [STDERR]: java.lang.NullPointerException
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.readBytes(CodecJOrbisFixed.java:587)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at com.creativemd.ambientsounds.CodecJOrbisFixed.read(CodecJOrbisFixed.java:358)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:691)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:928)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[21:45:18] [Thread-6/INFO]: [STDERR]: java.lang.NullPointerException
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.calculateDistance(SourceLWJGLOpenAL.java:732)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.positionChanged(SourceLWJGLOpenAL.java:385)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:698)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:928)
[21:45:18] [Thread-6/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
```
also when pausing / exit to main menus
```
[21:50:17] [main/INFO]: SoundSystem shutting down...
[21:50:22] [main/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[21:50:22] [main/ERROR]: Stream thread did not die!
```

**Comment by CreativeMD** [comment] 2017-07-20 09:07
This is a duplicate of an existing issue (https://github.com/CreativeMD/AmbientSounds/issues/7). Currently i'm waiting for the author of the paulscode engine to fix this issue, so there is nothing i can do. Just stick to the other issue, i will post there once i have some news.

**Closed as completed by CreativeMD** 2017-07-20 09:07 UTC
